### ISSUE TITLE
Support for more current/upcoming releases of simpleSAMLphp

### ISSUE THREAD

**Issue by MrSecure** [GEANT/simplesamlphp-module-selfregister#8]
I tried installing this module into SimpleSAMLphp (6b8b1d) using the composer process that's outlined in the current docs.   

When I enable the module, I get the following error message:
```
Fatal error: Call to undefined method SimpleSAML_Session::getInstance() in /var/simplesamlphp/modules/selfregister/www/index.php on line 4
```

This makes sense, given that the [1.14 release notes](https://github.com/simplesamlphp/simplesamlphp/blob/master/docs/simplesamlphp-upgrade-notes-1.14.txt)  indicate that the function is going away.

Are there any plans to update the module to work for 1.14?

Thank you.

**Comment by kaefert** [comment]
I just ran into this issue. Am I correct to assume that using SimpleSAMLphp version 1.13.2 should work as a workaround?

**Comment by edelahozuah** [comment]
@kaefert it seems to be a PR fixing this problem.

**Comment by dnmvisser** [comment]
Just merged several outstanding pull requests.
Module now works with latests (1.14.8 in my case).
